#+TITLE:     Harmony Project
#+AUTHOR:    Brian L. Troutwine
#+EMAIL:     brian@troutwine.us
#+DATE:      2010-07-01 Thu
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:nil *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+STYLE:    <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />

* Introduction

Harmony is a collaborative musical instrument: users connect
to an infinite Universe, add stars associated with a key
signature and orbit planets around the stars which incites
them to hum. User's connect together, and work together to
make beautiful music.

That's the plan, anyway.

* Dependencies

Better details to come. Languages:

+ Erlang :: harmonyd, the background server and persistent
            Universe.

+ Python :: harmony, the client and instrument.

* Source

The head repository for Harmony is to be found [[http://github.com/blt/Harmony][at GitHub]]. Fork
it!

[[www.mobydick.com][Moby Dick]]

* Download

There are no binaries available at this time.

#+BEGIN_HTML:
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-15917184-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type =
    'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ?
    'https://ssl' : 'http://www') +
    '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

</script>
#+END_HTML:
